<a href="https://colab.research.google.com/github/Shikhar-0809/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50])
addArr = arr + 2
print("Array after adding 2:",addArr)

multiplyArr = arr * 3
print("Array after multiplying by 3 : ",multiplyArr)

divideArr = arr / 2
print("Array after dividing by 2 : ",divideArr)


Array after adding 2: [12 22 32 42 52]
Array after multiplying by 3 :  [ 30  60  90 120 150]
Array after dividing by 2 :  [ 5. 10. 15. 20. 25.]


Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [4]:
arr = np.array([1,2,3,4,5])
revArray = arr[::-1]
print("Reversed Array : ",revArray)

Reversed Array :  [5 4 3 2 1]


Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
def mostFreq(arr):
  freqDict = {}

  for num in arr:
    if num in freqDict:
      freqDict[num] += 1

    else:
      freqDict[num] = 1


x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column **bold text**


In [9]:
import numpy as np

arr = np.array([[10, 20, 30],
               [40, 50, 60],
               [70, 80, 90]])

x = arr[0,1]
y = arr[2,0]

print("Element at first row , second column : ",x)
print("Element at third row , first column : ",y)

Element at first row , second column :  20
Element at third row , first column :  70


Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [11]:
import numpy as np

Shikhar = np.linspace(10,100,25)
print("Array : ",Shikhar)
print("Dimensions of Array : ",Shikhar.ndim)
print("Shape : ",Shikhar.shape)
print("Total Elements : ",Shikhar.size)
print("Data Type of Each Element : ",Shikhar.dtype)
print("Total Bytes Consumed : ",Shikhar.nbytes)

transposeArray = Shikhar.reshape(25,1)
print("Transpose Array : ",transposeArray)

TArray = Shikhar.T
print("Transpose Array(using T attribute): ",TArray)

print("Is T attribute same as reshape()?",np.array_equal(transposeArray,TArray))

Array :  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of Array :  1
Shape :  (25,)
Total Elements :  25
Data Type of Each Element :  float64
Total Bytes Consumed :  200
Transpose Array :  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose Array(using T attribute):  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Is T attribute same as reshape()? False




Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [16]:
import numpy as np

ucs420Shikhar = np.array([[10,20,30],
                         [40,50,60],
                         [70,80,90],
                         [15,20,35]])

meanVal = np.mean(ucs420Shikhar)
medianVal = np.median(ucs420Shikhar)
maxVal = np.max(ucs420Shikhar)
minVal = np.min(ucs420Shikhar)
uniqueElements = np.unique(ucs420Shikhar)

print("Mean : ",meanVal)
print("Median : ",medianVal)
print("Max : ",maxVal)
print("Min : ",minVal)
print("Unique : ",uniqueElements)

reshapedArr = ucs420Shikhar.reshape(4,3)
resizeArr = ucs420Shikhar.copy()
resizeArr.resize((2,3))


print("Reshaped Array : ",reshapedArr)
print("Resized Array : ",resizeArr)

Mean :  43.333333333333336
Median :  37.5
Max :  90
Min :  10
Unique :  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array :  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array :  [[10 20 30]
 [40 50 60]]
